package: yconverter
version: '2.0.0-alpha4'
author: Thomas Blum
supportpage:

page:
    title: 'translate:title'
    perm: admin[]
    icon: rex-icon fa-life-ring
    subpages:
        convert:
            title: 'translate:subpage_convert'
            subpages:
                redaxo: { title: 'translate:subpage_redaxo' }
                yform: { title: 'translate:subpage_yform' }
                seo42: { title: 'translate:subpage_seo42' }
        settings:
            title: 'translate:subpage_settings'
            subpages:
                general: { title: 'translate:subpage_settings_general' }
                ai: { title: 'translate:subpage_settings_ai' }

requires:
    redaxo: ^5.6.5

console_commands:
    'yconverter:run': 'YConverter\Console\RunCommand'
